/***************************************************************************
 *             __________               __   ___.
 *   Open      \______   \ ____   ____ |  | _\_ |__   _______  ___
 *   Source     |       _//  _ \_/ ___\|  |/ /| __ \ /  _ \  \/  /
 *   Jukebox    |    |   (  <_> )  \___|    < | \_\ (  <_> > <  <
 *   Firmware   |____|_  /\____/ \___  >__|_ \|___  /\____/__/\_ \
 *                     \/            \/     \/    \/            \/
 * This file was automatically generated by hwemulgen, DO NOT EDIT it.
 *
 * Copyright (C) 2012 by Amaury Pouly
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This software is distributed on an "AS IS" basis, WITHOUT WARRANTY OF ANY
 * KIND, either express or implied.
 *
 ****************************************************************************/
#ifndef __HWEMUL_SOC_HEADER__
#define __HWEMUL_SOC_HEADER__

#include "stddef.h"
#include "stdint.h"

#define HWEMUL_SOC_REG_HAS_SCT  (1 << 0)

struct hwemul_soc_reg_field_t
{
    const char *name;
    unsigned short first_bit, last_bit;
};

struct hwemul_soc_reg_t
{
    const char *name;
    uint32_t addr;
    uint32_t flags;
    size_t nr_fields;
    struct hwemul_soc_reg_field_t *fields_by_name[]; /* ordered by lexicographic order */
};

struct hwemul_soc_t
{
    const char *name;
    size_t nr_regs;
    struct hwemul_soc_reg_t *regs_by_name[]; /* ordered by lexicographic order */
};

struct hwemul_soc_list_t
{
    size_t nr_socs;
    struct hwemul_soc_t *socs[];
};

struct hwemul_soc_list_t *hwemul_get_soc_list(void);

#endif
