#
# common
#
CC=arm-none-eabi-gcc
LD=arm-none-eabi-gcc
AS=arm-none-eabi-gcc
OC=arm-none-eabi-objcopy
DEFINES=
INCLUDES=-I$(CURDIR)
GCCOPTS= -mthumb -mcpu=cortex-m3
BUILD_DIR=$(CURDIR)/build/
ROOT_DIR=$(CURDIR)/..

include ../hwstub.make
